syntax = "proto3";
package krdori.pb2.ce;

import "server/pb2/ce/suite_user.proto";
import "server/pb2/ce/user_event_box_gacha.proto";

message SuiteEventBoxGachaTopResponse {
  krdori.pb2.ce.SuiteUserGetResponse update_resources = 1;
  krdori.pb2.ce.EventBoxGachaTopResponse event_box_gacha_top_response = 2;
}

message SuiteEventBoxGachaResetResponse {
  krdori.pb2.ce.SuiteUserGetResponse update_resources = 1;
}

message SuiteEventBoxGachaSpinResponse {
  krdori.pb2.ce.SuiteUserGetResponse update_resources = 1;
  krdori.pb2.ce.EventBoxGachaSpinResponse event_box_gacha_spin_response = 2;
}
