# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: krdori/pb2/ce/master_player_resource.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'server/pb2/ce/master_player_resource.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*krdori/pb2/ce/master_player_resource.proto\x12\rkrdori.pb2.ce\"\x8d\x01\n\x0ePlayerResource\x12\x13\n\x0bresource_id\x18\x01 \x01(\r\x12\x15\n\rresource_type\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\r\x12\x10\n\x08lb_bonus\x18\x04 \x01(\r\x12\x11\n\tfirst_get\x18\x05 \x01(\x08\x12\x18\n\x10\x64uplicated_count\x18\x06 \x01(\r\"D\n\x12PlayerResourceList\x12.\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1d.krdori.pb2.ce.PlayerResource\"U\n\x15PlayerLimitedResource\x12\x13\n\x0bresource_id\x18\x01 \x01(\r\x12\x15\n\rresource_type\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\r\"R\n\x19PlayerLimitedResourceList\x12\x35\n\x07\x65ntries\x18\x01 \x03(\x0b\x32$.krdori.pb2.ce.PlayerLimitedResourceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.pb2.ce.master_player_resource_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYERRESOURCE']._serialized_start=62
  _globals['_PLAYERRESOURCE']._serialized_end=203
  _globals['_PLAYERRESOURCELIST']._serialized_start=205
  _globals['_PLAYERRESOURCELIST']._serialized_end=273
  _globals['_PLAYERLIMITEDRESOURCE']._serialized_start=275
  _globals['_PLAYERLIMITEDRESOURCE']._serialized_end=360
  _globals['_PLAYERLIMITEDRESOURCELIST']._serialized_start=362
  _globals['_PLAYERLIMITEDRESOURCELIST']._serialized_end=444
# @@protoc_insertion_point(module_scope)
