# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: krdori/pb2/ce/suite_user_friend.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'server/pb2/ce/suite_user_friend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from server.pb2.ce import suite_user_pb2 as krdori_dot_pb2_dot_ce_dot_suite__user__pb2
from server.pb2.ce import user_friend_pb2 as krdori_dot_pb2_dot_ce_dot_user__friend__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%krdori/pb2/ce/suite_user_friend.proto\x12\rkrdori.pb2.ce\x1a\x1ekrdori/pb2/ce/suite_user.proto\x1a\x1fkrdori/pb2/ce/user_friend.proto\"\x98\x01\n\x1aSuiteUserFriendTopResponse\x12=\n\x10update_resources\x18\x01 \x01(\x0b\x32#.krdori.pb2.ce.SuiteUserGetResponse\x12;\n\x12user_friend_detail\x18\x02 \x01(\x0b\x32\x1f.krdori.pb2.ce.UserFriendDetail\"\xb7\x01\n\x1dSuiteUserFriendResultResponse\x12=\n\x10update_resources\x18\x01 \x01(\x0b\x32#.krdori.pb2.ce.SuiteUserGetResponse\x12\x1a\n\x12\x66riend_result_code\x18\x02 \x01(\t\x12;\n\x12user_friend_detail\x18\x03 \x01(\x0b\x32\x1f.krdori.pb2.ce.UserFriendDetail\"`\n\x1fSuiteUserFriendRelationResponse\x12=\n\x10update_resources\x18\x01 \x01(\x0b\x32#.krdori.pb2.ce.SuiteUserGetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.pb2.ce.suite_user_friend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUITEUSERFRIENDTOPRESPONSE']._serialized_start=122
  _globals['_SUITEUSERFRIENDTOPRESPONSE']._serialized_end=274
  _globals['_SUITEUSERFRIENDRESULTRESPONSE']._serialized_start=277
  _globals['_SUITEUSERFRIENDRESULTRESPONSE']._serialized_end=460
  _globals['_SUITEUSERFRIENDRELATIONRESPONSE']._serialized_start=462
  _globals['_SUITEUSERFRIENDRELATIONRESPONSE']._serialized_end=558
# @@protoc_insertion_point(module_scope)
