# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: krdori/pb2/ce/suite_user_mission.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'server/pb2/ce/suite_user_mission.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from server.pb2.ce import master_player_resource_pb2 as krdori_dot_pb2_dot_ce_dot_master__player__resource__pb2
from server.pb2.ce import suite_user_pb2 as krdori_dot_pb2_dot_ce_dot_suite__user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&krdori/pb2/ce/suite_user_mission.proto\x12\rkrdori.pb2.ce\x1a*krdori/pb2/ce/master_player_resource.proto\x1a\x1ekrdori/pb2/ce/suite_user.proto\"\x8e\x01\n\rMissionReward\x12=\n\x10update_resources\x18\x01 \x01(\x0b\x32#.krdori.pb2.ce.SuiteUserGetResponse\x12>\n\x13mission_reward_list\x18\x02 \x01(\x0b\x32!.krdori.pb2.ce.PlayerResourceList\"M\n\x0cMissionClear\x12=\n\x10update_resources\x18\x01 \x01(\x0b\x32#.krdori.pb2.ce.SuiteUserGetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.pb2.ce.suite_user_mission_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MISSIONREWARD']._serialized_start=134
  _globals['_MISSIONREWARD']._serialized_end=276
  _globals['_MISSIONCLEAR']._serialized_start=278
  _globals['_MISSIONCLEAR']._serialized_end=355
# @@protoc_insertion_point(module_scope)
