# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: krdori/pb2/ce/suite_user_story.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'server/pb2/ce/suite_user_story.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from server.pb2.ce import suite_user_pb2 as krdori_dot_pb2_dot_ce_dot_suite__user__pb2
from server.pb2.ce import user_story_pb2 as krdori_dot_pb2_dot_ce_dot_user__story__pb2
from server.pb2.ce import user_band_story_pb2 as krdori_dot_pb2_dot_ce_dot_user__band__story__pb2
from server.pb2.ce import master_player_resource_pb2 as krdori_dot_pb2_dot_ce_dot_master__player__resource__pb2
from server.pb2.ce import newly_opened_content_pb2 as krdori_dot_pb2_dot_ce_dot_newly__opened__content__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$krdori/pb2/ce/suite_user_story.proto\x12\rkrdori.pb2.ce\x1a\x1ekrdori/pb2/ce/suite_user.proto\x1a\x1ekrdori/pb2/ce/user_story.proto\x1a#krdori/pb2/ce/user_band_story.proto\x1a*krdori/pb2/ce/master_player_resource.proto\x1a(krdori/pb2/ce/newly_opened_content.proto\"\x95\x02\n\x1aSuiteUserMainStoryResponse\x12=\n\x10update_resources\x18\x01 \x01(\x0b\x32#.krdori.pb2.ce.SuiteUserGetResponse\x12>\n\x14user_main_story_list\x18\x02 \x01(\x0b\x32 .krdori.pb2.ce.UserMainStoryList\x12\x32\n\x07rewards\x18\x03 \x01(\x0b\x32!.krdori.pb2.ce.PlayerResourceList\x12\x44\n\x15newly_opened_contents\x18\x04 \x01(\x0b\x32%.krdori.pb2.ce.NewlyOpenedContentList\"\x95\x02\n\x1aSuiteUserBandStoryResponse\x12=\n\x10update_resources\x18\x01 \x01(\x0b\x32#.krdori.pb2.ce.SuiteUserGetResponse\x12>\n\x14user_band_story_list\x18\x02 \x01(\x0b\x32 .krdori.pb2.ce.UserBandStoryList\x12\x32\n\x07rewards\x18\x03 \x01(\x0b\x32!.krdori.pb2.ce.PlayerResourceList\x12\x44\n\x15newly_opened_contents\x18\x04 \x01(\x0b\x32%.krdori.pb2.ce.NewlyOpenedContentListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.pb2.ce.suite_user_story_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUITEUSERMAINSTORYRESPONSE']._serialized_start=243
  _globals['_SUITEUSERMAINSTORYRESPONSE']._serialized_end=520
  _globals['_SUITEUSERBANDSTORYRESPONSE']._serialized_start=523
  _globals['_SUITEUSERBANDSTORYRESPONSE']._serialized_end=800
# @@protoc_insertion_point(module_scope)
