# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: krdori/pb2/ce/suite_user_panel_mission.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'server/pb2/ce/suite_user_panel_mission.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from server.pb2.ce import suite_user_pb2 as krdori_dot_pb2_dot_ce_dot_suite__user__pb2
from server.pb2.ce import master_player_resource_pb2 as krdori_dot_pb2_dot_ce_dot_master__player__resource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,krdori/pb2/ce/suite_user_panel_mission.proto\x12\rkrdori.pb2.ce\x1a\x1ekrdori/pb2/ce/suite_user.proto\x1a*krdori/pb2/ce/master_player_resource.proto\"\x94\x01\n\x15PanelMissionClearInfo\x12\x18\n\x10panel_mission_id\x18\x01 \x01(\r\x12\x11\n\tboard_seq\x18\x02 \x01(\r\x12\x16\n\x0epanel_seq_list\x18\x03 \x03(\r\x12\x36\n\x0breward_list\x18\x04 \x01(\x0b\x32!.krdori.pb2.ce.PlayerResourceList\"\xa6\x02\n\x17SuitePanelMissionReward\x12=\n\x10update_resources\x18\x01 \x01(\x0b\x32#.krdori.pb2.ce.SuiteUserGetResponse\x12@\n\x12\x63urrent_clear_info\x18\x02 \x01(\x0b\x32$.krdori.pb2.ce.PanelMissionClearInfo\x12\x43\n\x15next_board_clear_info\x18\x03 \x01(\x0b\x32$.krdori.pb2.ce.PanelMissionClearInfo\x12\x45\n\x1a\x62oard_complete_reward_list\x18\x04 \x01(\x0b\x32!.krdori.pb2.ce.PlayerResourceListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.pb2.ce.suite_user_panel_mission_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PANELMISSIONCLEARINFO']._serialized_start=140
  _globals['_PANELMISSIONCLEARINFO']._serialized_end=288
  _globals['_SUITEPANELMISSIONREWARD']._serialized_start=291
  _globals['_SUITEPANELMISSIONREWARD']._serialized_end=585
# @@protoc_insertion_point(module_scope)
