# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: krdori/pb2/ce/user_profile_situation.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'server/pb2/ce/user_profile_situation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*krdori/pb2/ce/user_profile_situation.proto\x12\rkrdori.pb2.ce\"t\n\x14UserProfileSituation\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x14\n\x0csituation_id\x18\x02 \x01(\r\x12\x0e\n\x06illust\x18\x03 \x01(\t\x12%\n\x1dview_profile_situation_status\x18\x04 \x01(\t\"j\n\x1bUserProfileSituationRequest\x12\x14\n\x0csituation_id\x18\x01 \x01(\r\x12\x0e\n\x06illust\x18\x02 \x01(\t\x12%\n\x1dview_profile_situation_status\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.pb2.ce.user_profile_situation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERPROFILESITUATION']._serialized_start=61
  _globals['_USERPROFILESITUATION']._serialized_end=177
  _globals['_USERPROFILESITUATIONREQUEST']._serialized_start=179
  _globals['_USERPROFILESITUATIONREQUEST']._serialized_end=285
# @@protoc_insertion_point(module_scope)
