# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: krdori/pb2/ce/user_shoplist_api.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'server/pb2/ce/user_shoplist_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from server.pb2.ce import newly_opened_content_pb2 as krdori_dot_pb2_dot_ce_dot_newly__opened__content__pb2
from server.pb2.ce import suite_user_pb2 as krdori_dot_pb2_dot_ce_dot_suite__user__pb2
from server.pb2.ce import updated_band_deck_rank_pb2 as krdori_dot_pb2_dot_ce_dot_updated__band__deck__rank__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%krdori/pb2/ce/user_shoplist_api.proto\x12\rkrdori.pb2.ce\x1a(krdori/pb2/ce/newly_opened_content.proto\x1a\x1ekrdori/pb2/ce/suite_user.proto\x1a*krdori/pb2/ce/updated_band_deck_rank.proto\"7\n\x13UserShoplistRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x0f\n\x07shop_id\x18\x02 \x01(\r\"\xd5\x01\n\x0cUserShoplist\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x0f\n\x07shop_id\x18\x02 \x01(\r\x12\x14\n\x0c\x61rea_item_id\x18\x03 \x01(\r\x12\x1a\n\x12\x61rea_item_category\x18\x04 \x01(\r\x12\x17\n\x0f\x61rea_item_level\x18\x05 \x01(\r\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x15\n\rshop_category\x18\x07 \x01(\t\x12\x0b\n\x03seq\x18\x08 \x01(\r\x12\x0e\n\x06\x61mount\x18\t \x01(\r\x12\x14\n\x0cshop_list_id\x18\n \x01(\r\"D\n\x14UserShoplistResponse\x12,\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1b.krdori.pb2.ce.UserShoplist\"@\n\x10UserShoplistList\x12,\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1b.krdori.pb2.ce.UserShoplist\"\x15\n\x13UserAreaItemRequest\"\x16\n\x14UserAreaItemResponse\"\xa6\x02\n\x19SuiteUserShoplistResponse\x12=\n\x10update_resources\x18\x01 \x01(\x0b\x32#.krdori.pb2.ce.SuiteUserGetResponse\x12\x37\n\x0euser_shop_list\x18\x02 \x01(\x0b\x32\x1f.krdori.pb2.ce.UserShoplistList\x12\x44\n\x15newly_opened_contents\x18\x03 \x01(\x0b\x32%.krdori.pb2.ce.NewlyOpenedContentList\x12K\n\x1bupdated_band_deck_rank_list\x18\x04 \x01(\x0b\x32&.krdori.pb2.ce.UpdatedBandDeckRankListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.pb2.ce.user_shoplist_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERSHOPLISTREQUEST']._serialized_start=174
  _globals['_USERSHOPLISTREQUEST']._serialized_end=229
  _globals['_USERSHOPLIST']._serialized_start=232
  _globals['_USERSHOPLIST']._serialized_end=445
  _globals['_USERSHOPLISTRESPONSE']._serialized_start=447
  _globals['_USERSHOPLISTRESPONSE']._serialized_end=515
  _globals['_USERSHOPLISTLIST']._serialized_start=517
  _globals['_USERSHOPLISTLIST']._serialized_end=581
  _globals['_USERAREAITEMREQUEST']._serialized_start=583
  _globals['_USERAREAITEMREQUEST']._serialized_end=604
  _globals['_USERAREAITEMRESPONSE']._serialized_start=606
  _globals['_USERAREAITEMRESPONSE']._serialized_end=628
  _globals['_SUITEUSERSHOPLISTRESPONSE']._serialized_start=631
  _globals['_SUITEUSERSHOPLISTRESPONSE']._serialized_end=925
# @@protoc_insertion_point(module_scope)
