# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: krdori/pb2/ce/user_deco_equipment.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'server/pb2/ce/user_deco_equipment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'server/pb2/ce/user_deco_equipment.proto\x12\rkrdori.pb2.ce\"\xae\x01\n\x11UserDecoEquipment\x12\x0f\n\x07user_id\x18\x01 \x01(\r\x12\x15\n\rdeco_frame_id\x18\x02 \x01(\r\x12\x15\n\rdeco_pins_id1\x18\x03 \x01(\r\x12\x15\n\rdeco_pins_id2\x18\x04 \x01(\r\x12\x15\n\rdeco_pins_id3\x18\x05 \x01(\r\x12\x15\n\rdeco_pins_id4\x18\x06 \x01(\r\x12\x15\n\rdeco_pins_id5\x18\x07 \x01(\r\"\x9b\x02\n\x1cUserDecoEquipmentRequestBody\x12\x15\n\rdeco_frame_id\x18\x01 \x01(\r\x12\x1a\n\rdeco_pins_id1\x18\x02 \x01(\rH\x00\x88\x01\x01\x12\x1a\n\rdeco_pins_id2\x18\x03 \x01(\rH\x01\x88\x01\x01\x12\x1a\n\rdeco_pins_id3\x18\x04 \x01(\rH\x02\x88\x01\x01\x12\x1a\n\rdeco_pins_id4\x18\x05 \x01(\rH\x03\x88\x01\x01\x12\x1a\n\rdeco_pins_id5\x18\x06 \x01(\rH\x04\x88\x01\x01\x42\x10\n\x0e_deco_pins_id1B\x10\n\x0e_deco_pins_id2B\x10\n\x0e_deco_pins_id3B\x10\n\x0e_deco_pins_id4B\x10\n\x0e_deco_pins_id5b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.pb2.ce.user_deco_equipment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERDECOEQUIPMENT']._serialized_start=59
  _globals['_USERDECOEQUIPMENT']._serialized_end=233
  _globals['_USERDECOEQUIPMENTREQUESTBODY']._serialized_start=236
  _globals['_USERDECOEQUIPMENTREQUESTBODY']._serialized_end=519
# @@protoc_insertion_point(module_scope)
