# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: krdori/pb2/ce/user_area_item.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'server/pb2/ce/user_area_item.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from server.pb2.ce import newly_opened_content_pb2 as krdori_dot_pb2_dot_ce_dot_newly__opened__content__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"server/pb2/ce/user_area_item.proto\x12\rkrdori.pb2.ce\x1a(krdori/pb2/ce/newly_opened_content.proto\"`\n\x0cUserAreaItem\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x14\n\x0c\x61rea_item_id\x18\x02 \x01(\r\x12\x1a\n\x12\x61rea_item_category\x18\x03 \x01(\r\x12\r\n\x05level\x18\x04 \x01(\r\"\xe2\x01\n\x0fUserAreaItemMap\x12<\n\x07\x65ntries\x18\x01 \x03(\x0b\x32+.krdori.pb2.ce.UserAreaItemMap.EntriesEntry\x12\x44\n\x15newly_opened_contents\x18\x02 \x01(\x0b\x32%.krdori.pb2.ce.NewlyOpenedContentList\x1aK\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.krdori.pb2.ce.UserAreaItem:\x02\x38\x01\"@\n\x10UserAreaItemList\x12,\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1b.krdori.pb2.ce.UserAreaItemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.pb2.ce.user_area_item_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERAREAITEMMAP_ENTRIESENTRY']._loaded_options = None
  _globals['_USERAREAITEMMAP_ENTRIESENTRY']._serialized_options = b'8\001'
  _globals['_USERAREAITEM']._serialized_start=95
  _globals['_USERAREAITEM']._serialized_end=191
  _globals['_USERAREAITEMMAP']._serialized_start=194
  _globals['_USERAREAITEMMAP']._serialized_end=420
  _globals['_USERAREAITEMMAP_ENTRIESENTRY']._serialized_start=345
  _globals['_USERAREAITEMMAP_ENTRIESENTRY']._serialized_end=420
  _globals['_USERAREAITEMLIST']._serialized_start=422
  _globals['_USERAREAITEMLIST']._serialized_end=486
# @@protoc_insertion_point(module_scope)
