# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: krdori/pb2/ce/user_gacha_api.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'server/pb2/ce/user_gacha_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from server.pb2.ce import master_player_resource_pb2 as krdori_dot_pb2_dot_ce_dot_master__player__resource__pb2
from server.pb2.ce import suite_user_pb2 as krdori_dot_pb2_dot_ce_dot_suite__user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"server/pb2/ce/user_gacha_api.proto\x12\rkrdori.pb2.ce\x1a*krdori/pb2/ce/master_player_resource.proto\x1a\x1ekrdori/pb2/ce/suite_user.proto\"V\n\x10UserGachaRequest\x12\x10\n\x08gacha_id\x18\x01 \x01(\r\x12\x0f\n\x07\x62\x61nd_id\x18\x02 \x01(\r\x12\x19\n\x11payment_method_id\x18\x04 \x01(\rJ\x04\x08\x03\x10\x04\"?\n\x11UserGachaResponse\x12\x14\n\x0csituation_id\x18\x01 \x01(\r\x12\x14\n\x0cis_first_get\x18\x02 \x01(\x08\"\x8e\x02\n\x15UserGachaResponseList\x12\x31\n\x07\x65ntries\x18\x01 \x03(\x0b\x32 .krdori.pb2.ce.UserGachaResponse\x12\x31\n\x06\x65xtras\x18\x02 \x01(\x0b\x32!.krdori.pb2.ce.PlayerResourceList\x12\x19\n\x11\x62\x65\x66ore_gacha_seal\x18\x04 \x01(\r\x12\x18\n\x10\x61\x66ter_gacha_seal\x18\x05 \x01(\r\x12\x18\n\x10\x62\x65\x66ore_star_seal\x18\x06 \x01(\r\x12\x17\n\x0f\x61\x66ter_star_seal\x18\x07 \x01(\r\x12\x1b\n\x13\x64uplicate_star_seal\x18\t \x01(\rJ\x04\x08\x03\x10\x04J\x04\x08\x08\x10\t\"\xa0\x01\n\x16SuiteUserGachaResponse\x12;\n\rgacha_results\x18\x02 \x01(\x0b\x32$.krdori.pb2.ce.UserGachaResponseList\x12=\n\x10update_resources\x18\x04 \x01(\x0b\x32#.krdori.pb2.ce.SuiteUserGetResponseJ\x04\x08\x01\x10\x02J\x04\x08\x03\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.pb2.ce.user_gacha_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERGACHAREQUEST']._serialized_start=129
  _globals['_USERGACHAREQUEST']._serialized_end=215
  _globals['_USERGACHARESPONSE']._serialized_start=217
  _globals['_USERGACHARESPONSE']._serialized_end=280
  _globals['_USERGACHARESPONSELIST']._serialized_start=283
  _globals['_USERGACHARESPONSELIST']._serialized_end=553
  _globals['_SUITEUSERGACHARESPONSE']._serialized_start=556
  _globals['_SUITEUSERGACHARESPONSE']._serialized_end=716
# @@protoc_insertion_point(module_scope)
