# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: krdori/pb2/ce/user_present.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'server/pb2/ce/user_present.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from server.pb2.ce import master_player_resource_pb2 as krdori_dot_pb2_dot_ce_dot_master__player__resource__pb2
from server.pb2.ce import newly_opened_content_pb2 as krdori_dot_pb2_dot_ce_dot_newly__opened__content__pb2
from server.pb2.ce import suite_user_pb2 as krdori_dot_pb2_dot_ce_dot_suite__user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n krdori/pb2/ce/user_present.proto\x12\rkrdori.pb2.ce\x1a*krdori/pb2/ce/master_player_resource.proto\x1a(krdori/pb2/ce/newly_opened_content.proto\x1a\x1ekrdori/pb2/ce/suite_user.proto\"\xbc\x01\n\x0bUserPresent\x12\x12\n\npresent_id\x18\x01 \x01(\x04\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\x12\x15\n\rresource_type\x18\x03 \x01(\t\x12\x13\n\x0bresource_id\x18\x04 \x01(\r\x12\x10\n\x08quantity\x18\x05 \x01(\r\x12\x0e\n\x06reason\x18\x06 \x01(\t\x12\x17\n\nexpired_at\x18\x07 \x01(\x04H\x00\x88\x01\x01\x12\x12\n\ncreated_at\x18\x08 \x01(\x04\x42\r\n\x0b_expired_at\":\n\nPagination\x12\r\n\x05start\x18\x01 \x01(\x04\x12\r\n\x05limit\x18\x02 \x01(\r\x12\x0e\n\x06record\x18\x03 \x01(\x04\"m\n\x0fUserPresentList\x12+\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1a.krdori.pb2.ce.UserPresent\x12-\n\npagination\x18\x02 \x01(\x0b\x32\x19.krdori.pb2.ce.Pagination\"\xd2\x01\n\x15ObtainPresentResponse\x12=\n\x10update_resources\x18\x01 \x01(\x0b\x32#.krdori.pb2.ce.SuiteUserGetResponse\x12\x34\n\tresources\x18\x02 \x01(\x0b\x32!.krdori.pb2.ce.PlayerResourceList\x12\x44\n\x15newly_opened_contents\x18\x03 \x01(\x0b\x32%.krdori.pb2.ce.NewlyOpenedContentListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.pb2.ce.user_present_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERPRESENT']._serialized_start=170
  _globals['_USERPRESENT']._serialized_end=358
  _globals['_PAGINATION']._serialized_start=360
  _globals['_PAGINATION']._serialized_end=418
  _globals['_USERPRESENTLIST']._serialized_start=420
  _globals['_USERPRESENTLIST']._serialized_end=529
  _globals['_OBTAINPRESENTRESPONSE']._serialized_start=532
  _globals['_OBTAINPRESENTRESPONSE']._serialized_end=742
# @@protoc_insertion_point(module_scope)
