# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: krdori/pb2/ce/user_multi_room_friend_recruitment.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'server/pb2/ce/user_multi_room_friend_recruitment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6krdori/pb2/ce/user_multi_room_friend_recruitment.proto\x12\rkrdori.pb2.ce\"U\n-UserMultiRoomFriendRecruitmentLiveTopResponse\x12$\n\x1crecruitmented_live_type_list\x18\x01 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.pb2.ce.user_multi_room_friend_recruitment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERMULTIROOMFRIENDRECRUITMENTLIVETOPRESPONSE']._serialized_start=73
  _globals['_USERMULTIROOMFRIENDRECRUITMENTLIVETOPRESPONSE']._serialized_end=158
# @@protoc_insertion_point(module_scope)
