# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: krdori/pb2/ce/user_deck_api.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'server/pb2/ce/user_deck_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from server.pb2.ce import suite_user_pb2 as krdori_dot_pb2_dot_ce_dot_suite__user__pb2
from server.pb2.ce import user_deck_pb2 as krdori_dot_pb2_dot_ce_dot_user__deck__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!krdori/pb2/ce/user_deck_api.proto\x12\rkrdori.pb2.ce\x1a\x1ekrdori/pb2/ce/suite_user.proto\x1a\x1dkrdori/pb2/ce/user_deck.proto\"\xf9\x01\n\x13\x45\x64itUserDeckRequest\x12\x11\n\tdeck_name\x18\x02 \x01(\t\x12\x13\n\x06leader\x18\x03 \x01(\rH\x00\x88\x01\x01\x12\x14\n\x07member1\x18\x04 \x01(\rH\x01\x88\x01\x01\x12\x14\n\x07member2\x18\x05 \x01(\rH\x02\x88\x01\x01\x12\x14\n\x07member3\x18\x06 \x01(\rH\x03\x88\x01\x01\x12\x14\n\x07member4\x18\x07 \x01(\rH\x04\x88\x01\x01\x12\x14\n\x0cis_recommend\x18\t \x01(\x08\x12\x11\n\tdeck_type\x18\n \x01(\tB\t\n\x07_leaderB\n\n\x08_member1B\n\n\x08_member2B\n\n\x08_member3B\n\n\x08_member4\"U\n\x14\x45\x64itUserDeckResponse\x12=\n\x10update_resources\x18\x01 \x01(\x0b\x32#.krdori.pb2.ce.SuiteUserGetResponse\"\x17\n\x15UserDeckMapGetRequest\"\xa6\x01\n\x16UserDeckMapGetResponse\x12\x43\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x32.krdori.pb2.ce.UserDeckMapGetResponse.EntriesEntry\x1aG\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.krdori.pb2.ce.UserDeck:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.pb2.ce.user_deck_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERDECKMAPGETRESPONSE_ENTRIESENTRY']._loaded_options = None
  _globals['_USERDECKMAPGETRESPONSE_ENTRIESENTRY']._serialized_options = b'8\001'
  _globals['_EDITUSERDECKREQUEST']._serialized_start=116
  _globals['_EDITUSERDECKREQUEST']._serialized_end=365
  _globals['_EDITUSERDECKRESPONSE']._serialized_start=367
  _globals['_EDITUSERDECKRESPONSE']._serialized_end=452
  _globals['_USERDECKMAPGETREQUEST']._serialized_start=454
  _globals['_USERDECKMAPGETREQUEST']._serialized_end=477
  _globals['_USERDECKMAPGETRESPONSE']._serialized_start=480
  _globals['_USERDECKMAPGETRESPONSE']._serialized_end=646
  _globals['_USERDECKMAPGETRESPONSE_ENTRIESENTRY']._serialized_start=575
  _globals['_USERDECKMAPGETRESPONSE_ENTRIESENTRY']._serialized_end=646
# @@protoc_insertion_point(module_scope)
